### ISSUE TITLE
Deployment using GitHub Pages

### ISSUE THREAD

**Issue by lordksix** [lordksix/portafolio-app#11]
Link of the deployed webpage using GitHub Pages:
- https://lordksix.github.io/portafolio-app/

**Comment by wayungi** [comment]
Hi @lordksix , 

![image](https://user-images.githubusercontent.com/99656687/220082459-c1b049c7-5498-42e7-942b-ec7a05d3e603.png)

Great work, your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

**Remember: Every finish line 🏁  is the beginning of a new race 🐎** 

## Highlights
- [ ] Project successfully deployed using GitHub pages ✔️ 

## Optional suggestions
- [ ] I noticed your desktop version has a horizontal scroll bar at the bottom. This means that part of your content is wider than the device's width. You can improve the user experience by making sure your page fits without the need to scroll on any screen size. This offers a better user experience for your website visitors, what's your take on the subject 🤔 ?
![width](https://user-images.githubusercontent.com/99656687/229455049-534ae270-b0c5-42c6-970f-d5b70a82acbd.png)


_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by lordksix** [comment]
Hello, @wayungi  

Thank you for the approval and the feedback.
